[package]
name = "reg-lang"
version = "0.0.1-alpha"
authors = ["Julien Higginson <J.H.Gipson62@gmail.com>"]
description = "A simple, fast and experimental VM for Reg-Lang."
license = "GPL-3.0 license"
repository = "https://github.com/RedGear-Studio/Reg-Lang"

[dependencies]
pwintln = "0.1.3"
