[package]
name = "atlas-test"
version = "0.3.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atlas-core = { path = "../atlas-core" }
clap = { version = "4.4.8", features = ["derive"] }
