[package]
name = "reg-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reg-lang-vm = { path = "../reg-lang-vm" }
reg-lang-compiler = { path = "../reg-lang-compiler" }