[package]
name = "atlas-printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atlas-syntax = { path = "../atlas-syntax"}
atlas-misc = { path = "../atlas-misc" }
